// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsSpotifyAuthPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsSpotifyAuthPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsSpotifyAuthPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashSpotifyAuthPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashSpotifyAuthPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashSpotifyAuthPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct AuthenticateRequest: Hashable {
  var clientId: String
  var redirectUri: String
  var scopes: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthenticateRequest? {
    let clientId = pigeonVar_list[0] as! String
    let redirectUri = pigeonVar_list[1] as! String
    let scopes = pigeonVar_list[2] as! [String]

    return AuthenticateRequest(
      clientId: clientId,
      redirectUri: redirectUri,
      scopes: scopes
    )
  }
  func toList() -> [Any?] {
    return [
      clientId,
      redirectUri,
      scopes,
    ]
  }
  static func == (lhs: AuthenticateRequest, rhs: AuthenticateRequest) -> Bool {
    return deepEqualsSpotifyAuthPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashSpotifyAuthPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AuthenticateReply: Hashable {
  var code: String? = nil
  var refreshToken: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthenticateReply? {
    let code: String? = nilOrValue(pigeonVar_list[0])
    let refreshToken: String? = nilOrValue(pigeonVar_list[1])

    return AuthenticateReply(
      code: code,
      refreshToken: refreshToken
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      refreshToken,
    ]
  }
  static func == (lhs: AuthenticateReply, rhs: AuthenticateReply) -> Bool {
    return deepEqualsSpotifyAuthPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashSpotifyAuthPigeon(value: toList(), hasher: &hasher)
  }
}

private class SpotifyAuthPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AuthenticateRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return AuthenticateReply.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SpotifyAuthPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AuthenticateRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AuthenticateReply {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SpotifyAuthPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SpotifyAuthPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SpotifyAuthPigeonPigeonCodecWriter(data: data)
  }
}

class SpotifyAuthPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SpotifyAuthPigeonPigeonCodec(readerWriter: SpotifyAuthPigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SpotifyAuthApi {
  func canAuthenticateUsingSpotifyApp() throws -> Bool
  func authenticate(request: AuthenticateRequest, completion: @escaping (Result<AuthenticateReply, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SpotifyAuthApiSetup {
  static var codec: FlutterStandardMessageCodec { SpotifyAuthPigeonPigeonCodec.shared }
  /// Sets up an instance of `SpotifyAuthApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SpotifyAuthApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let canAuthenticateUsingSpotifyAppChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.spotify_auth.SpotifyAuthApi.canAuthenticateUsingSpotifyApp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      canAuthenticateUsingSpotifyAppChannel.setMessageHandler { _, reply in
        do {
          let result = try api.canAuthenticateUsingSpotifyApp()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      canAuthenticateUsingSpotifyAppChannel.setMessageHandler(nil)
    }
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.spotify_auth.SpotifyAuthApi.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! AuthenticateRequest
        api.authenticate(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
  }
}
