include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  exclude:
    - "**/*.g.dart"