name: spotify_auth
description: "A library to authenticate with Spotify."
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.3.2

flutter:
  plugin:
    platforms:
      android:
        package: org.volumio.spotify_auth
        pluginClass: SpotifyAuthPlugin
      ios:
        pluginClass: SpotifyAuthPlugin
