// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package org.volumio.spotify_auth

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SpotifyAuthPigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class AuthenticateRequest (
  val clientId: String,
  val redirectUri: String,
  val scopes: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthenticateRequest {
      val clientId = pigeonVar_list[0] as String
      val redirectUri = pigeonVar_list[1] as String
      val scopes = pigeonVar_list[2] as List<String>
      return AuthenticateRequest(clientId, redirectUri, scopes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientId,
      redirectUri,
      scopes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AuthenticateRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return SpotifyAuthPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AuthenticateReply (
  val code: String? = null,
  val refreshToken: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthenticateReply {
      val code = pigeonVar_list[0] as String?
      val refreshToken = pigeonVar_list[1] as String?
      return AuthenticateReply(code, refreshToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      refreshToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AuthenticateReply) {
      return false
    }
    if (this === other) {
      return true
    }
    return SpotifyAuthPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class SpotifyAuthPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthenticateRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthenticateReply.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AuthenticateRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AuthenticateReply -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SpotifyAuthApi {
  fun canAuthenticateUsingSpotifyApp(): Boolean
  fun authenticate(request: AuthenticateRequest, callback: (Result<AuthenticateReply>) -> Unit)

  companion object {
    /** The codec used by SpotifyAuthApi. */
    val codec: MessageCodec<Any?> by lazy {
      SpotifyAuthPigeonPigeonCodec()
    }
    /** Sets up an instance of `SpotifyAuthApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SpotifyAuthApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.spotify_auth.SpotifyAuthApi.canAuthenticateUsingSpotifyApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.canAuthenticateUsingSpotifyApp())
            } catch (exception: Throwable) {
              SpotifyAuthPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.spotify_auth.SpotifyAuthApi.authenticate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as AuthenticateRequest
            api.authenticate(requestArg) { result: Result<AuthenticateReply> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SpotifyAuthPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SpotifyAuthPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
